// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesSystem.Entities
{
    [Index(nameof(SaleRefundID), nameof(PartID), Name = "UQ_SaleRefundDetails_SaleRefundIDPartID", IsUnique = true)]
    public partial class SaleRefundDetail
    {
        [Key]
        public int SaleRefundDetailID { get; set; }
        public int SaleRefundID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [StringLength(150)]
        public string Reason { get; set; }

        [ForeignKey(nameof(PartID))]
        [InverseProperty("SaleRefundDetails")]
        public virtual Part Part { get; set; }
        [ForeignKey(nameof(SaleRefundID))]
        [InverseProperty("SaleRefundDetails")]
        public virtual SaleRefund SaleRefund { get; set; }
    }
}