// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesSystem.Entities
{
    public partial class SaleRefund
    {
        public SaleRefund()
        {
            SaleRefundDetails = new HashSet<SaleRefundDetail>();
        }

        [Key]
        public int SaleRefundID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SaleRefundDate { get; set; }
        public int SaleID { get; set; }
        public int EmployeeID { get; set; }
        [Column(TypeName = "money")]
        public decimal TaxAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal SubTotal { get; set; }

        [ForeignKey(nameof(EmployeeID))]
        [InverseProperty("SaleRefunds")]
        public virtual Employee Employee { get; set; }
        [ForeignKey(nameof(SaleID))]
        [InverseProperty("SaleRefunds")]
        public virtual Sale Sale { get; set; }
        [InverseProperty(nameof(SaleRefundDetail.SaleRefund))]
        public virtual ICollection<SaleRefundDetail> SaleRefundDetails { get; set; }
    }
}