// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RecievingSystem.Entities
{
    public partial class ReceiveOrderDetail
    {
        [Key]
        public int ReceiveOrderDetailID { get; set; }
        public int ReceiveOrderID { get; set; }
        public int PurchaseOrderDetailID { get; set; }
        public int QuantityReceived { get; set; }

        [ForeignKey(nameof(PurchaseOrderDetailID))]
        [InverseProperty("ReceiveOrderDetails")]
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        [ForeignKey(nameof(ReceiveOrderID))]
        [InverseProperty("ReceiveOrderDetails")]
        public virtual ReceiveOrder ReceiveOrder { get; set; }
    }
}